version: '{branch}-{build}'
skip_non_tags: true
platform:
- x86
- x64
init:
- cmd: IF %APPVEYOR_REPO_TAG%==true appveyor UpdateBuild -Version %APPVEYOR_REPO_TAG_NAME%-%APPVEYOR_BUILD_NUMBER%
before_build:
- cmd: >-
    appveyor DownloadFile http://tjaberg.com/fds%APPVEYOR_REPO_TAG_NAME:.=%.zip

    7z x *.zip

    DEL *.zip
build_script:
- cmd: build.bat
after_build:
- cmd: 7z a fds-%Platform%.zip *.exe
artifacts:
- path: '*.zip'
  name: fds
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: El+n+uSEJ5lyM3PcYsbY9PW6hV5voxAmeQ2Odlx8x57JFHZtLWnWG+6bHpfF/+EA
  artifact: /.*\.zip/
  on:
    APPVEYOR_REPO_TAG: true
